language: node_js
node_js:
  - 6.10.2
script: node_modules/karma/bin/karma start karma.conf.js --single-run
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm install